### PR TITLE
Upgrade CA dependencies: PHP 8.3, Laravel 11, PHPUnit 11

### PR DESCRIPTION
**Pull request by emmachughes**

### CODE REVIEW

**Comment by chrieinv** [comment]
Issue with `Integrity constraint violation: 19 NOT NULL constraint failed: h5p_contents.license` is because the `license` field is not nullable. It was set as nullable when created, but the migration `2016_02_25_154000_increase_text_license.php`, changing the length of the `license` field, does not specifying that the field can be nullable, so it seems that SQLite then defaulted back to not nullable but MariaDB kept it as nullable.

**Comment by emmachughes** [comment]
Sounds like a problem caused by <https://laravel.com/docs/11.x/upgrade#modifying-columns>, perhaps?

**Comment by chrieinv** [comment]
Seems so. This is a big change, it will be an issue with all new installations. It's possible to fix the migrations, but there are over 100 migrations, so maybe the [Database squash](https://laravel.com/docs/11.x/migrations#squashing-migrations) on a pre Laravel 11 setup is a solution?

**Comment by emmachughes** [comment]
I think we should fix the migrations instead. It doesn't seem like it would be too hard.

The columns that have `->change()` statements are:

- `cerpus_contents_shares.email`
- `content_languages.language_code`
- `h5p_contents.filtered`
- `h5p_contents.license`
- `h5p_contents.parameters`
- `h5p_contents.user_id`
- `h5p_contents_user_data.data`
- `h5p_contents_user_data.user_id`
- `h5p_results.user_id`
- `ndla_article_import_statuses.message`
- `ndla_article_import_statuses.ndla_id`
- `ndla_id_mappers.language_code`
- `question_set_question_answers.answer_text`
- `question_set_questions.question_text`
- `question_sets.title`

**Comment by emmachughes** [comment]
Have verified that the resulting database schema is identical to that of an existing install.

**Review by chrieinv — APPROVED** [review]

**Pull request merged**
